### ISSUE TITLE
Copy single file?

### ISSUE THREAD

**Issue by MMRandy** [MathieuLoutre/grunt-aws-s3#63] opened 2015-03-07 19:33 UTC
I don't see an easy way to copy a single file given that the src attribute will be used as a prefix for the destination file.  Am I missing something here?  Trying the following cmd:

```
				backup: {
					files:[
						{src: 'xxx/js/yyy.js', dest: 'xxx/js/zzz.js', action: 'copy'},
					]
				},
```

**Comment by MathieuLoutre** [comment] 2015-03-07 20:50
What happens when you do this? It gets created but using the whole of src as the path?
The copy action is pretty new in the plugin and I haven't used it much myself, but what you describe should be possible. Unless I'm mistaken, the src attribute is used a prefix when _listing_ data, it shouldn't be (I think) used when copying the data. Let me know if I'm wrong.

Otherwise, and it's a little bit of a workaround, you could use `exclude` to match the one file you want with `flipExclude` to `true` to make sure it only matches this one file.

**Comment by MMRandy** [comment] 2015-03-07 21:38
If no src is specified, it'll throw for copy commands:
````
Fatal error: Specify a "src" but not a "cwd" for copies
````

And the exclude with the flipExclude set to true will experience the same result, namely that the src file (whether from the src arrib or the result of the exclude and flip) will be appended to the dest attrib and saved as the copied filename.  Seems like a bug but haven't dug into the code.

**Comment by MathieuLoutre** [comment] 2015-03-07 21:52
Oooh, I get it. I didn't think you'd want to change the name of the file as it's copied




Not sure how to do it right now but this should be supported I guess.

**Comment by MathieuLoutre** [comment] 2015-10-25 21:39
Duplicate of #68. Closing for now, discussion will continue on other issue.

**Closed by MathieuLoutre** 2015-10-25 21:39 UTC
